# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91521d173ed2cfc712a556a0df7a0151ae77158b69176f49c60e4f4db344ce6a89b0203617645ac671dc3cdfa587dbb006a4f75362d9df4cd2f3b841f34b7bff

test:
  secret_key_base: b1226da4ccb57613cb2e10689c05a6fe123cf79208ca634ecc4451703c6f45aed55819d24fad8f872bb0df74a155a4417f1987e37c28970e17cfee7756d60f43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
